[package]
name = "abc219"
version = "0.1.0"
edition = "2021"

[dependencies]
ac-library-rs = "=0.1.1"
itertools = "=0.11.0"
num = "=0.4.1"
permutohedron = "=0.2.4"
proconio = { version = "=0.4.5", features = ["derive"] }
rand = "=0.8.5"
regex = "=1.9.1"
superslice = "=1.0.0"
